name             "s9y"
maintainer       "E Camden Fisher"
maintainer_email "fish@fishnix.net"
license          "Apache 2.0"
description      "Installs/Configures s9y"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.4"
depends "apache2"
depends "php5"
depends "git"
depends "mysql"
depends "database"