name             's9y'
maintainer       'E Camden Fisher'
maintainer_email 'camden@northpage.com'
license          'Apache 2.0'
description      'Installs/Configures s9y'
long_description 'Installs/Configures s9y blogging platform'
version          '1.0.0'

depends 'yum', '~> 3.4.1'
depends 'yum-epel', '~> 0.5.2'
depends 'yum-mysql-community', '~> 0.1.10'
depends 'apache2', '~> 3.0.0'
depends 'php', '~> 1.5.0'
depends 'mysql', '~> 6.0.0'
depends 'git', '~> 4.1.0'

